public enum SettingsCopy {
    public static let general = "General"
    public static let resources = "Resources"
    public static let kubernetes = "Kubernetes"
    public static let files = "Files"
    public static let network = "Network"
    public static let advanced = "Advanced"
    public static let privacy = "Privacy"
    public static let updates = "Updates"

    public static let launchAtLogin = "Launch at login"
    public static let keepRunning = "Keep cluster running when window closes"
    public static let setCurrentContext = "Set current-context on start"
    public static let startClusterAtLogin = "Start cluster at login"
    public static let appliesNextStart = "Applies on next cluster start."
    public static let resetRequired = "Reset required."
    public static let balloon = "Memory balloon"
    public static let balloonUnsupported = "experimental, not supported in v1"
    public static let diskCapLocked = "Grow and shrink are not in v1."
    public static let k3sVersion = "Kubernetes version"
    public static let clusterName = "Cluster name"
    public static let clusterNameReset = "Reset required to rename."
    public static let kubeVirtAddon = "KubeVirt addon"
    public static let kubeVirtForced = "Eureka profiles turn KubeVirt on."
    public static let disableBundled = "Disable bundled"
    public static let coreDNSRequired = "CoreDNS is not optional. Helm-controller is not a disable checkbox."
    public static let storageClass = "Storage class"
    public static let storageClassValue = "local-path"
    public static let hostUID = "Host uid:gid"
    public static let noHomeShare = "No default $HOME share."
    public static let addFolder = "Add Folder…"
    public static let apiBind = "API bind"
    public static let apiBindValue = "127.0.0.1"
    public static let apiPort = "API port"
    public static let ingress = "Ingress"
    public static let ingressValue = "8080 / 8443"
    public static let publishNodePorts = "Publish NodePorts to 127.0.0.1"
    public static let virtctlHelp = "Eureka SSH uses virtctl, not these NodePorts."
    public static let publishL1SSH = "Publish guest sshd to 127.0.0.1:22022"
    public static let publishL1SSHHelp =
        "Eureka jump for Builderdash proxy_conf. Never host port 22. Needs a guest image with sshd."
    public static let registries = "registries.yaml"
    public static let registriesHelp = "Mirrors and insecure registries. Passwords stay in Keychain."
    public static let registryHost = "Registry"
    public static let registryUser = "Username"
    public static let registryPassword = "Password"
    public static let saveRegistry = "Save in Keychain"
    public static let guestSSH = "Guest SSH debug"
    public static let resetFactory = "Reset Cluster…"
    public static let telemetry = "Telemetry"
    public static let telemetryOff =
        "Off. Vendor network: Sparkle and GitHub Releases. Not Docker Hub for system images."
    public static let proxyNote =
        "Guest HTTP(S)_PROXY comes from this Mac’s system proxy, not from gvproxy."
}
